<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML & DL</b></center>

<center><b><h1>Lab - 8</b></center>    
<pre>    

# Step 1: Import Libraries
This step imports all necessary libraries for data processing, visualization, and machine learning.

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Step 2: Load the Dataset
Load Given dataset -  heart.csv

In [62]:
df = pd.read_csv("heart.csv")

# Step 3: Data Overview
In this step, we examine the dataset structure, summary statistics, and check for missing values.

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [64]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000


# Step 4: Univariate Analysis
Here we visualize the distribution of each feature using histograms.

In [65]:
df.hist(figsize=(12,12))

array([[<Axes: title={'center': 'age'}>, <Axes: title={'center': 'sex'}>,
        <Axes: title={'center': 'cp'}>,
        <Axes: title={'center': 'trestbps'}>],
       [<Axes: title={'center': 'chol'}>,
        <Axes: title={'center': 'fbs'}>,
        <Axes: title={'center': 'restecg'}>,
        <Axes: title={'center': 'thalach'}>],
       [<Axes: title={'center': 'exang'}>,
        <Axes: title={'center': 'oldpeak'}>,
        <Axes: title={'center': 'slope'}>,
        <Axes: title={'center': 'ca'}>],
       [<Axes: title={'center': 'thal'}>,
        <Axes: title={'center': 'target'}>, <Axes: >, <Axes: >]],
      dtype=object)

# Step 5: Bivariate Analysis
This step involves exploring the correlations between features using a heatmap.

In [66]:
import seaborn as sns

In [67]:
%matplotlib qt

In [68]:
sns.heatmap(df.corr(),annot=True)

<Axes: >

# Step 6: Outlier Detection
We visualize potential outliers using boxplots.

In [69]:
df.boxplot()

ValueError: The number of FixedLocator locations (21), usually from a call to set_ticks, does not match the number of labels (14).

# Step 7: Split Data into Training and Testing Sets
The dataset is split into training and testing sets for model evaluation.

In [ ]:
x = df.iloc[::,:-1:]

In [ ]:
y = df['target']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=80)

# Step 8: Train Decision Tree
We train a Decision Tree Classifier on the training data. You have to also check for KNeighborsClassifier and  GaussianNB

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model = DecisionTreeClassifier()

In [ ]:
model.fit(x_train,y_train)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
y_predict = model.predict(x_test)

In [ ]:
accuracy_score(y_test,y_predict)

In [ ]:
model.score(x_test,y_test)

# Cross Validation

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
k = KFold(n_splits=10)

In [ ]:
x

In [ ]:
for train_index,test_index in k.split(x):
    x_train,x_test = x.values[train_index],x.values[test_index]
    y_train,y_test = y[train_index],y[test_index]
    model1 = DecisionTreeClassifier()
    model1.fit(x_train,y_train)
    print(model1.score(x_test,y_test))
    

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(model,x,y,cv=10)

In [ ]:
import numpy as np

In [ ]:
x1 = np.arange(1,11).reshape(-1,1)

In [72]:
y1 = np.array([0,1,0,1,0,1,0,1,0,1])

In [73]:
for i,j in k.split(x1):
    print("<------>")
    print(x1[i])
    print(x1[j])
    x_train,x_test = x1[i],x1[j]
    y_train,y_test = y1[i],y1[j]

<------>
[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[1]]
<------>
[[ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[2]]
<------>
[[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[3]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[4]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[5]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[6]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]]
[[7]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]]
[[8]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]]
[[9]]
<------>
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[10]]


<------>
[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[1]]
<------>
[[ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[2]]
<------>
[[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[3]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[4]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[5]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[6]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]]
[[7]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]]
[[8]]
<------>
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]]
[[9]]
<------>
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[10]]


# BS4 | web Scraping to get Data

In [1]:
import requests
import bs4

In [2]:
req = requests.get('https://darshan.ac.in/faculty-list/btech-computer')
print('Status Code:',req.status_code)

Status Code: 200


In [3]:
req.text

'\r\n\r\n\r\n<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n    \r\n    <!-- Required Meta Tags Always Come First -->\r\n    <meta charset="utf-8">\r\n    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">\r\n    <meta http-equiv="x-ua-compatible" content="ie=edge">\r\n\r\n        <title>Faculty List | B.Tech. (CSE) | Darshan University, Rajkot</title>\r\n        <meta name="keywords" />\r\n        <meta name="description" />\r\n        <meta name="author" content="Darshan University" />\r\n\r\n    <!-- Favicon -->\r\n    <!-- <link rel="shortcut icon" href="~/Content/media/favicon2.svg"> -->\r\n\r\n    <link rel="icon" type="image/png" sizes="48x48" href="/Content/media/favicon-48x48.png">\r\n    <link rel="icon" type="image/png" sizes="32x32" href="/Content/media/favicon-32x32.png">\r\n    <link rel="icon" type="image/png" sizes="16x16" href="/Content/media/favicon-16x16.png">\r\n    <link rel="icon" href="/favicon.ico" type="image/x-icon">\r\n\r

In [4]:
soup = bs4.BeautifulSoup(req.text,"html.parser")
soup


<!DOCTYPE html>

<html lang="en">
<head>
<!-- Required Meta Tags Always Come First -->
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
<meta content="ie=edge" http-equiv="x-ua-compatible"/>
<title>Faculty List | B.Tech. (CSE) | Darshan University, Rajkot</title>
<meta name="keywords">
<meta name="description">
<meta content="Darshan University" name="author">
<!-- Favicon -->
<!-- <link rel="shortcut icon" href="~/Content/media/favicon2.svg"> -->
<link href="/Content/media/favicon-48x48.png" rel="icon" sizes="48x48" type="image/png"/>
<link href="/Content/media/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/Content/media/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon.ico" rel="icon" type="image/x-icon"/>
<!-- Google Fonts -->
<link href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500

In [5]:
data = soup.select("body > main > div:nth-child(5) > div > div > div > div > div")
len(data)

31

In [6]:
print('Faculty Name','--->','Joining Date:\n')
for f in data:
    name = f.select("h2")[0].text.strip()
    joiningData = f.select('span')[5].text.strip()
    print(name,'--->',joiningData)

Faculty Name ---> Joining Date:

Dr. Gopi Sanghani ---> Jul-2012
Dr. Nilesh Gambhava ---> Jul-2009
Dr. Pradyumansinh Jadeja ---> Jul-2009
Prof. Maulik Trivedi ---> Jun-2009
Prof. Firoz Sherasiya ---> Dec-2022
Prof. Rupesh Vaishnav ---> May-2013
Prof. Arjun Bala ---> Jul-2013
Prof. Naimish Vadodariya ---> Jun-2015
Prof. Vaseem Ghada ---> Aug-2021
Dr. Sharon Mohtra ---> Jul-2022
Prof. Dixita Kagathara ---> Jul-2009
Prof. Swati Sharma ---> May-2013
Prof. Mayur Padia ---> Jul-2011
Prof. Ashok Badresiya ---> Dec-2022
Prof. UmeshKumar Thoriya ---> Jul-2015
Prof. Jayesh Vagadiya ---> Jul-2015
Prof. Krunal Vyas ---> Jun-2018
Prof. Rajkumar Gondaliya ---> Feb-2017
Prof. Mehul Bhundiya ---> Aug-2018
Prof. Jay Dhamsaniya ---> Jul-2012
Prof. Vishal Kansagara ---> Nov-2021
Prof. Shruti Maniar ---> Dec-2021
Prof. Dharmik Vasiyani ---> Nov-2021
Prof. Devangi Kotak ---> Jul-2022
Prof. Bhushan Joshi ---> Jun-2022
Prof. Hemang Chath ---> Sep-2021
Prof. Charvin Kothia ---> Nov-2020
Prof. Madhuresh Fichad