<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>    

# Decision Tree Classifier

In [89]:
from sklearn.datasets import load_iris 

# Import iris data ser using sklearn

In [90]:
data = load_iris()

In [91]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [92]:
type(data)

sklearn.utils._bunch.Bunch

# Importing the libraries

In [93]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree

# Divide the data into input and output

In [94]:
X = data['data']

In [95]:
y = data['target']

In [96]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Splitting the dataset into the Training set and Test set

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [99]:
print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


# Fitting DecisionTreeClassifier   on dataset

In [100]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

In [101]:
model = DecisionTreeClassifier()

In [102]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [103]:
from sklearn import tree

In [104]:
%matplotlib qt

In [105]:
tree.plot_tree(model)

[Text(0.3333333333333333, 0.9166666666666666, 'x[3] <= 0.75\ngini = 0.666\nsamples = 105\nvalue = [37, 33, 35]'),
 Text(0.16666666666666666, 0.75, 'gini = 0.0\nsamples = 37\nvalue = [37, 0, 0]'),
 Text(0.25, 0.8333333333333333, 'True  '),
 Text(0.5, 0.75, 'x[2] <= 4.75\ngini = 0.5\nsamples = 68\nvalue = [0, 33, 35]'),
 Text(0.41666666666666663, 0.8333333333333333, '  False'),
 Text(0.3333333333333333, 0.5833333333333334, 'gini = 0.0\nsamples = 32\nvalue = [0, 32, 0]'),
 Text(0.6666666666666666, 0.5833333333333334, 'x[3] <= 1.7\ngini = 0.054\nsamples = 36\nvalue = [0, 1, 35]'),
 Text(0.5, 0.4166666666666667, 'x[3] <= 1.55\ngini = 0.32\nsamples = 5\nvalue = [0, 1, 4]'),
 Text(0.3333333333333333, 0.25, 'gini = 0.0\nsamples = 3\nvalue = [0, 0, 3]'),
 Text(0.6666666666666666, 0.25, 'x[0] <= 6.6\ngini = 0.5\nsamples = 2\nvalue = [0, 1, 1]'),
 Text(0.5, 0.08333333333333333, 'gini = 0.0\nsamples = 1\nvalue = [0, 1, 0]'),
 Text(0.8333333333333334, 0.08333333333333333, 'gini = 0.0\nsamples = 1\n

In [106]:
%whos

Variable                 Type                      Data/Info
------------------------------------------------------------
DecisionTreeClassifier   ABCMeta                   <class 'sklearn.tree._cla<...>.DecisionTreeClassifier'>
X                        ndarray                   150x4: 600 elems, type `float64`, 4800 bytes
X_test                   ndarray                   45x4: 180 elems, type `float64`, 1440 bytes
X_train                  ndarray                   105x4: 420 elems, type `float64`, 3360 bytes
accuracy_score           function                  <function accuracy_score at 0x0000012E1AF67F60>
classification_report    function                  <function classification_<...>rt at 0x0000012E1AFA1440>
cm                       ndarray                   2x2: 4 elems, type `int64`, 32 bytes
cols                     list                      n=5
confusion_matrix         function                  <function confusion_matrix at 0x0000012E1AFA00E0>
data                     Bunch    

# Predict the x_test 

In [107]:
model.predict(X_test)

array([2, 0, 2, 0, 0, 1, 2, 2, 2, 1, 2, 0, 2, 2, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 0, 1, 2, 2, 2, 2, 0, 1, 1, 2, 2, 2,
       2])

In [108]:
y_test

array([1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 2, 0, 2, 2, 2, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 2, 1, 1, 0, 0, 1, 2, 0, 0, 1, 1, 2, 2, 2, 0, 1, 1, 2, 2, 2,
       1])

In [109]:
model.score(X_train,y_train)

1.0

In [110]:
model.score(X_test,y_test)

0.8666666666666667

# Import diabetes.csv dataset 

In [111]:
df = pd.read_csv("diabetes.csv")

In [112]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Check the distribution of the target

In [113]:
df["Outcome"].value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [114]:
cols = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]
df[cols] = df[cols].replace(0,np.nan)
df[cols].isna().sum()

Glucose            5
BloodPressure     35
SkinThickness    227
Insulin          374
BMI               11
dtype: int64

# Check for missing values

In [115]:
df.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# Fill missing values with median

In [116]:
df[cols] = df[cols].fillna(
    df[cols].median()
)

In [117]:
df[cols].isna().sum()

Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
dtype: int64

# Visualize Distributions

In [118]:
import seaborn as sns
sns.pairplot(df, hue="Outcome")

# Convert Targer data into interger code

In [119]:
df['Outcome'] = df['Outcome'].map({"Diabetic":1,"Non Diabetic":0})

In [120]:
import matplotlib.pyplot as plt
sns.heatmap(df.corr(),annot=True,cmap='coolwarm')
plt.show()

In [121]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    125.0  33.6   
1              1     85.0           66.0           29.0    125.0  26.6   
2              8    183.0           64.0           29.0    125.0  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0    125.0  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0           29.0    125.0  30.1   
767            1     93.0           70.0           31.0    125.0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

# Divide the data into input and output

In [122]:
from sklearn.model_selection import train_test_split

In [123]:
X = df.drop(columns=["Outcome"])
y = df["Outcome"]

# Splitting the dataset into the Training set and Test set

In [124]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

# Create Model

In [125]:
model = DecisionTreeClassifier() 

# Fitting DecisionTreeClassifier   on dataset

In [126]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [127]:
from sklearn import tree
tree.plot_tree(model)

[Text(0.5656490223930482, 0.9666666666666667, 'x[1] <= 154.5\ngini = 0.455\nsamples = 537\nvalue = [349, 188]'),
 Text(0.22755472927807488, 0.9, 'x[7] <= 28.5\ngini = 0.383\nsamples = 454\nvalue = [337, 117]'),
 Text(0.3966018758355615, 0.9333333333333333, 'True  '),
 Text(0.10695187165775401, 0.8333333333333334, 'x[1] <= 127.5\ngini = 0.22\nsamples = 238\nvalue = [208, 30]'),
 Text(0.06417112299465241, 0.7666666666666667, 'x[5] <= 49.1\ngini = 0.117\nsamples = 192\nvalue = [180, 12]'),
 Text(0.053475935828877004, 0.7, 'x[5] <= 31.4\ngini = 0.1\nsamples = 190\nvalue = [180, 10]'),
 Text(0.03208556149732621, 0.6333333333333333, 'x[4] <= 48.5\ngini = 0.018\nsamples = 108\nvalue = [107, 1]'),
 Text(0.0213903743315508, 0.5666666666666667, 'x[6] <= 0.63\ngini = 0.142\nsamples = 13\nvalue = [12, 1]'),
 Text(0.0106951871657754, 0.5, 'gini = 0.0\nsamples = 12\nvalue = [12, 0]'),
 Text(0.03208556149732621, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.0427807486631016, 0.566666666666

# Predict the x_test 

In [128]:
y_predict = model.predict(X_test)

# Display Training Accuracy

In [129]:
from sklearn.metrics import accuracy_score

y_train_predict = model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_predict)

print("Training Accuracy:", train_accuracy)


Training Accuracy: 1.0


# Display Test Accuracy

In [130]:
from sklearn.metrics import accuracy_score

y_test_predict = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_predict)

print("Test Accuracy:", test_accuracy)


Test Accuracy: 0.6926406926406926


# Confusion Matrix

In [131]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [132]:
cm = confusion_matrix(y_test,y_predict,)
cm

array([[109,  42],
       [ 29,  51]])

In [133]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.79      0.72      0.75       151
           1       0.55      0.64      0.59        80

    accuracy                           0.69       231
   macro avg       0.67      0.68      0.67       231
weighted avg       0.71      0.69      0.70       231



# Save Model State

In [134]:
import pickle

In [135]:
with open('model.pkl','wb') as file:
    pickle.dump(model,file)

# Load Model from Disk

In [136]:
with open('model.pkl','rb') as file:
    loaded_model = pickle.load(file)

In [137]:
loaded_model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [138]:
from sklearn.metrics import classification_report

In [139]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.79      0.72      0.75       151
           1       0.55      0.64      0.59        80

    accuracy                           0.69       231
   macro avg       0.67      0.68      0.67       231
weighted avg       0.71      0.69      0.70       231

